# Generated by Django 2.2 on 2019-05-10 16:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picture', '0002_picture_image'),
    ]

    operations = [
        migrations.AlterField(
            model_name='picture',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='picture_image/'),
        ),
    ]
