# Generated by Django 2.2 on 2019-04-26 05:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('read_statistics', '0002_readdetail'),
    ]

    operations = [
        migrations.DeleteModel(
            name='ReadDetail',
        ),
    ]
