# Generated by Django 2.2 on 2019-05-12 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_delete_readnum'),
    ]

    operations = [
        migrations.AddField(
            model_name='blog',
            name='image',
            field=models.ImageField(default='default.jpg', upload_to='blog_image/'),
        ),
    ]
